[package]
name = "zktls_verifier"
type = "bin"
authors = ["zklawd"]
compiler_version = ">=1.0.0"

[dependencies]
att_verifier_lib = { tag = "main", git = "https://github.com/zklawd/zktls-verification-noir", directory = "att_verifier_lib" }
sha256 = { tag = "v0.3.0", git = "https://github.com/noir-lang/sha256" }
keccak256 = { tag = "v0.1.3", git = "https://github.com/noir-lang/keccak256" }
