[package]
name = "zktls_verifier"
type = "bin"
authors = ["zklawd"]
compiler_version = ">=1.0.0"

[dependencies]
att_verifier_lib = { tag = "main", git = "https://github.com/zklawd/zktls-verification-noir", directory = "att_verifier_lib" }
